views/buyback.py
import json
import time
from itertools import chain
import re
import math

from flask import Blueprint, render_template, g, request, session, redirect, url_for, abort

from bson.objectid import ObjectId
import bson.errors

from views.auth import requires_sso
from helpers import conversions, eve_central, caches

buyback = Blueprint("buyback", __name__, template_folder="templates")


def price_calc(names, character_id, jf_rate=0):
    item_list = g.mongo.db.items.find({"name": {"$in": names}})
    id_list = g.mongo.db.items.find({"name": {"$in": names}}).distinct("_id")

    mineral_list = {}
    item_materials = conversions.refine_calc(id_list, character_id)
    material_id_list = set()
    non_refine_list = []
    for item in item_list:
        if item["materials"] and (not item["meta"] or item["meta"] < 4):
            for material_id, material_amount in item_materials[item["_id"]].items():
                material_id_list.add(material_id)
                mineral_list.setdefault(material_id, 0)
                mineral_list[material_id] += material_amount
        else:
            item_materials[item["_id"]] = {}
            non_refine_list.append(item["_id"])
    market_prices, prices_usable = eve_central.market_hub_prices(list(mineral_list.keys()) +
                                                                 list(item_materials.keys()) +
                                                                 non_refine_list)

    # Material info for volume
    material_info_db = g.mongo.db.items.find({"_id": {"$in": list(material_id_list)}})
    material_volumes = {}
    for material_info in material_info_db:
        material_volumes[material_info["_id"]] = material_info.get("volume", 0)

    # Tax Checks
    taxes_list = g.mongo.db.taxes.find({"_id": {"$in": list(item_materials.keys()) + non_refine_list}})
    tax_definition = {}
    for tax_item in taxes_list:
        tax_definition[tax_item["_id"]] = tax_item["tax"]
    refine_preferences = g.mongo.db.preferences.find_one({"_id": "buyback_yield"})
    if refine_preferences:
        default_tax = refine_preferences.get("tax", 0)
        default_refine_tax = refine_preferences.get("tax_refine", 0)
    else:
        default_tax = 0
        default_refine_tax = 0

    # Refined Calculations
    calculations = {}
    for key, value in item_materials.items():
        item_cost = 0
        volume = 0
        for material_id, material_amount in value.items():
            item_cost += material_amount * market_prices[material_id]["buy"]
            volume += material_amount * material_volumes[material_id]
        jf_price = jf_rate * volume
        calculations[key] = {"total": item_cost * (1 - tax_definition.get(key, default_refine_tax) / 100),
                             "no_tax": item_cost,
                             "sell": market_prices[key]["sell"],
                             "buy": market_prices[key]["buy"],
                             "volume": volume,
                             "jf_price": jf_price,
                             "delta_sell": item_cost - (market_prices[key]["sell"] - jf_price),
                             "delta_buy": item_cost - (market_prices[key]["buy"] - jf_price),
                             "tax": tax_definition.get(key, default_refine_tax)}

    # Info for non-refined
    non_refine_info_db = g.mongo.db.items.find({"_id": {"$in": non_refine_list}})

    # Non-refined modules
    for non_refine_item in non_refine_info_db:
        calculations[non_refine_item["_id"]] = {
            "total": market_prices[non_refine_item["_id"]]["buy"] * (
                1 - tax_definition.get(non_refine_item["_id"], default_tax) / 100),
            "no_tax": market_prices[non_refine_item["_id"]]["buy"],
            "sell": market_prices[non_refine_item["_id"]]["sell"],
            "buy": market_prices[non_refine_item["_id"]]["buy"],
            "volume": non_refine_item["volume"],
            "jf_price": non_refine_item["volume"] * jf_rate,
            "delta_sell": item_cost - (market_prices[non_refine_item["_id"]]["sell"] - jf_price),
            "delta_buy": item_cost - (market_prices[non_refine_item["_id"]]["buy"] - jf_price),
            "tax": tax_definition.get(non_refine_item["_id"], default_tax)
        }

    mineral_prices = {}
    for mineral in mineral_list.keys():
        mineral_prices[mineral] = market_prices[mineral]

    return calculations, mineral_prices, item_materials, prices_usable


@buyback.route("/", methods=["GET", "POST"])
def home():
    prices_usable = True
    quote_ran = False
    error_id = request.args.get("error_id")
    if not error_id:
        error_list = []
    else:
        error_list = ["Quote of id '{}' cannot be found. It's probably really old.".format(error_id)]

    if request.method == "POST" or request.form.get("action") == "quote":
        quote_ran = True
        with open("configs/base.json", "r") as base_config_file:
            base_config = json.load(base_config_file)

        # JF Calculations
        hub_to_home = base_config["market_hub_station"] * 100000000 + base_config["home_station"]
        selected_route_info = g.mongo.db.jf_routes.find_one({"_id": hub_to_home})
        if selected_route_info:
            rate_info = conversions.valid_value(selected_route_info["prices"], time.time())
            if session.get("UI_Corporation"):
                jf_rate = rate_info["corp"]
            else:
                jf_rate = rate_info["general"]
        else:
            jf_rate = 0

        # Parsing
        if request.form.get("action") != "quote":
            input_string = request.form.get("input")
        else:
            input_string = request.form.get("saved_input").replace("|", "\n")
        item_names, item_input, item_qty, extra_errors = conversions.manual_parsing(input_string)

        refine_character = g.mongo.db.preferences.find_one({"_id": "refine_character"})
        if refine_character:
            refine_id = refine_character["character_id"]
        else:
            refine_id = 0
        item_prices, material_prices_list, item_materials, prices_usable = price_calc(item_input, refine_id, jf_rate)
        item_list = g.mongo.db.items.find({"name": {"$in": item_input}})

        # Headers
        material_id_list = list(set(chain(*[x.keys() for x in item_materials.values()])))
        material_name_db = g.mongo.db.items.find({"_id": {"$in": material_id_list}})
        material_header = []
        for material_name in material_name_db:
            material_header.append((material_name["_id"], material_name["name"]))
        material_header.sort(key=lambda x: x[0])
        item_table = [["Name", "Qty"] + [x[1] for x in material_header]]
        price_table = [[
            "Name",
            "Qty",
            "Our Price / Item",
            "Tax %",
            "No Tax",
            base_config["market_hub_name"] + " buy",
            base_config["market_hub_name"] + " sell",
            "Volume",
            "JF Price",
            "Sub Total"
        ]]

        # Items
        total_price = 0
        total_buy_delta = 0
        total_sell_delta = 0
        parsed_item_list = []
        for output_item in item_list:
            parsed_item_list.append(output_item["name"].upper())

            jf_price = output_item["volume"] * jf_rate

            # Deltas
            buy_delta = item_prices[output_item["_id"]]["total"] - (item_prices[output_item["_id"]]["buy"] - jf_price)
            sell_delta = item_prices[output_item["_id"]]["total"] - (item_prices[output_item["_id"]]["sell"] - jf_price)

            total_price += item_prices[output_item["_id"]]["total"] * item_qty[output_item["name"].upper()]
            total_buy_delta += buy_delta * item_qty[output_item["name"].upper()]
            total_sell_delta += sell_delta * item_qty[output_item["name"].upper()]

            materials_row = [math.floor(item_materials[output_item["_id"]].get(x[0], 0) *
                                        item_qty[output_item["name"].upper()])
                             for x in material_header]
            # noinspection PyTypeChecker
            item_table.append([output_item["name"], item_qty[output_item["name"].upper()]] + materials_row)
            price_table.append([
                output_item["name"],
                item_qty[output_item["name"].upper()],
                item_prices[output_item["_id"]]["total"],
                item_prices[output_item["_id"]]["tax"],
                item_prices[output_item["_id"]]["no_tax"],
                item_prices[output_item["_id"]]["buy"],
                item_prices[output_item["_id"]]["sell"],
                output_item["volume"],
                jf_price,
                item_prices[output_item["_id"]]["total"] * item_qty[output_item["name"].upper()]
            ])

        # Check if all items parsed
        for item in item_names:
            if item.upper() not in parsed_item_list:
                error_list.append("The item '{}' could not be found.".format(item))

        # Materials
        material_table = [["Name", base_config["market_hub_name"] + " buy", base_config["market_hub_name"] + " sell"]]
        for material_id, material_name in material_header:
            material_table.append([material_name, material_prices_list[material_id]["buy"],
                                   material_prices_list[material_id]["sell"]])

        # Formatting
        item_table = [item_table[0]] + [row[:1] + ["{:,.02f}".format(value) for value in row[1:]]
                                        for row in item_table[1:]]
        price_table = [price_table[0]] + [row[:2] + ["{:,.02f}".format(value) for value in row[2:]]
                                          for row in price_table[1:]]
        material_table = [material_table[0]] + [row[:1] + ["{:,.02f}".format(value) for value in row[1:]]
                                                for row in material_table[1:]]
        total_buy_delta = "{:,.02f}".format(total_buy_delta)

views/corp.py
import json
import datetime

from flask import Blueprint, render_template, g, session
from bson.objectid import ObjectId

from views.auth import requires_sso

corp = Blueprint("corp", __name__, template_folder="templates")


@corp.route("/")
@requires_sso("corporation")
def home():
    with open("configs/base.json", "r") as base_config_file:
        base_config = json.load(base_config_file)

    # Missing APIs
    missing_apis = []
    corp_ids = []
    api_characters = set()
    # Determine accounts in corp
    for user_info in g.mongo.db.users.find({"corporation_id": base_config["corporation_id"]}):
        if g.mongo.db.security_characters.find_one({"_id": user_info["character_id"]}):
            corp_ids.append(user_info["_id"])
    # Determine characters with an api
    for api_user in g.mongo.db.api_keys.find({"_id": {"$in": corp_ids}}):
        for key in api_user["keys"]:
            api_characters.add(key["character_name"])
    # Determine characters in corp without an api from a corp account
    for corp_character in g.mongo.db.security_characters.find():
        if corp_character["name"] not in api_characters:
            missing_apis.append(corp_character["name"])

    # Personal Invoices
    one_month_oid = ObjectId.from_datetime(datetime.datetime.today() - datetime.timedelta(30))
    invoice_table = []
    for invoice in g.mongo.db.invoices.find({"_id": {"$gt": one_month_oid}, "user": session["CharacterOwnerHash"]}):
        invoice_status = invoice.get("status", "Not Processed")
        invoice_timestamp = ObjectId(invoice["_id"]).generation_time.strftime("%Y-%m-%d %H:%M:%S")
        invoice_color = ""
        if invoice_status == "Shipping - Completed":
            invoice_color = "primary"
        elif invoice_status == "Processing" or invoice_status.startswith("Shipping"):
            invoice_color = "warning"
        elif invoice_status in ["Failed", "Rejected"]:
            invoice_color = "danger"
        invoice_table.append([invoice_color, invoice_timestamp, invoice["_id"], invoice["jf_end"],
                              "{:,.02f}".format(invoice["order_total"]), invoice.get("marketeer"), invoice_status])

    # Away from EVE
    db_vacation = g.mongo.db.personals.find({"vacation": {"$exists": True}})
    away_from_eve = []
    for character in db_vacation:
        if character["corporation_id"] == base_config["corporation_id"]:
            away_from_eve.append([character["character_name"], character["vacation"], character["vacation_date"]])

    return render_template("corp.html", away_from_eve=away_from_eve, invoice_table=invoice_table,
                           missing_apis=missing_apis)

views/security/__init__.py
__author__ = 'slacker'

templates/account.html
{% extends "base.html" %}
{% block head %}
{{super()}}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon_jf.ico') }}">
{% endblock head %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% if vacation %}
            <div class="alert alert-danger" role="alert">You currently have "Away from EVE" mode enabled.</div>
            {% endif %}
            {% if keys %}
            <div class="alert alert-danger" role="alert">
                Key(s) with ID {{keys}} has an error. It has been marked as invalid and can no longer be used on the site. Please input a new key.
            </div>
            {% endif %}
            {% if message %}
            <div class="alert alert-success" role="alert">
                {{message}}
            </div>
            {% endif %}
            {% with flash_list = get_flashed_messages(with_categories=true) %}
            {% if flash_list %}
            {% for category, flash in flash_list %}
            {% if category == "message" %}
            <div class="alert alert-success" role="alert">
                {{flash}}
            </div>
            {% else %}
            <div class="alert alert-danger" role="alert">
                {{flash}}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item">
                    <img src="{{image_list[0]}}" alt="Character">
                    <img src="{{image_list[1]}}" alt="Corporation">
                    <img src="{{image_list[2]}}" alt="Alliance">
                </li>
                <li class="list-group-item"><b>Site ID:</b> {{user_info[0]}}</li>
                <li class="list-group-item"><b>Character:</b> {{user_info[1]}}</li>
                <li class="list-group-item"><b>Corporation:</b> {{user_info[2]}}</li>
                <li class="list-group-item"><b>Alliance:</b> {{user_info[3]}}</li>
                <li class="list-group-item"><b>Email:</b> {{user_info[4]}}</li>
                <li class="list-group-item"><b>Mumble ID:</b> {{user_info[5]}}</li>
                <li class="list-group-item"><b>Discord ID:</b> {{user_info[6]}}</li>
                <li class="list-group-item">
                    <b>Recruitment IDs:</b>
                    {% for id in recruitment_ids %}
                    <a href="{{url_for('recruitment.form', key=id)}}">{{id}}</a>
                    {% endfor %}
                </li>
            </ul>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Approved Roles</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        {% if given_roles %}
                        {% for role in given_roles %}
                        <li>{{role}}</li>
                        {% endfor %}
                        {% else %}
                        <li>None</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div>
                <form method="get">
                    <label>Away From EVE</label>
                    {% if vacation %}
                    <div class="form-group">
                        <textarea class="form-control" rows="5" name="text" disabled>{{vacation_text}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="date">Estimated Return Date</label>
                        <input id="date" name="date" type="date" value="{{vacation_date}}" disabled/>
                    </div>
                    <div class="form-group">
                        <button name="action" type="submit" class="btn btn-danger" value="disable">Disable</button>
                    </div>
                    {% else %}
                    <div class="form-group">
                        <textarea class="form-control" rows="5" name="text"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="date2">Estimated Return Date: (MM/DD/YYYY)</label>
                        <input id="date2" name="date" type="date" />
                    </div>
                    <div class="form-group">
                        <button name="action" type="submit" class="btn btn-warning" value="enable">Enable</button>
                    </div>
                    {% endif %}
                </form>
            </div>
            <div class="form-group">
                <form method="post" class="form-inline">
                    <div class="form-group">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Email</span>
                                <input class="form-control" placeholder="user@example.com" name="email" type="email">
                            </div>
                        </div>
                        <div class="form-group">
                            <button name="action" type="submit" class="btn btn-warning" value="email">Edit</button>
                        </div>
                    </div>
                </form>
                <form method="post" class="form-inline">
                    <div class="form-group">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">Mumble ID</span>
                                <input class="form-control" placeholder="123" name="mumble">
                            </div>
                        </div>
                        <div class="form-group">
                            <button name="action" type="submit" class="btn btn-warning" value="mumble">Edit</button>
                        </div>
                    </div>
                </form>
                <form method="post" class="form-inline">
                    <div class="form-group">
                        <input class="form-control" name="discord_id" type="hidden" value="{{user_info[6]}}">
                        <input class="form-control" name="nsfw" type="hidden" value="{{nsfw}}">
                        <a class="btn btn-primary" href="{{url_for('auth.discord_redirect')}}" role="button">Connect Discord</a>
                        {% if not user_info[6] %}
                        <button name="action" type="submit" class="btn btn-warning" value="nsfw" disabled>Enable NSFW</button>
                        {% elif nsfw %}
                        <button name="action" type="submit" class="btn btn-warning" value="nsfw">Disable NSFW</button>
                        {% else %}
                        <button name="action" type="submit" class="btn btn-warning" value="nsfw">Enable NSFW</button>
                        {% endif %}
                    </div>
                </form>
            </div>
            {% for error in error_list %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
            {% endfor %}
            <div>
                <form method="post">
                    <label> Add New API:
                        <a href="http://community.eveonline.com/support/api-key/CreatePredefined?accessMask={{access_mask}}" target="_blank">
                        Predefined Link
                        </a>
                        [Check No Expiry]
                    </label>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">Key ID</span>
                            <input class="form-control" placeholder="Key ID" name="key_id">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">vCode</span>
                            <input class="form-control" placeholder="vCode" name="vcode">
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="action" type="submit" class="btn btn-primary" value="add">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <ul class="nav nav-tabs">
            <li><a data-toggle="tab" href="#apis">APIs</a></li>
            <li class="active"><a data-toggle="tab" href="#invoices">Invoices</a></li>
        </ul>
        <div class="tab-content">
            <div id="apis" class="tab-pane">
                <div class="col-md-12">
                    <h2>All APIs</h2>
                    <form method="post" class="form-inline">
                        <div class="form-group">
                            <button name="action" type="submit" class="btn btn-warning" value="validate">Validate All APIs</button>
                        </div>
                    </form>
                    <table class="table table-hover table-condensed datatables dt-responsive" width="100%">
                        <thead>
                        <tr>
                            <th>Char ID</th>
                            <th>Char Name</th>
                            <th>Key ID</th>
                            <th>vCode</th>
                            <th>Cached Until</th>
                            <th>Valid</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key in associated_keys %}
                        <tr class="{{'danger' if not key[-1]}}">
                            {% for info in key %}
                            <td>{{info}}</td>
                            {% endfor %}
                            <td>
                                <form method="post">
                                    <input class="form-control" name="key_id" type="hidden" value="{{key[2]}}">
                                    <input class="form-control" name="vcode" type="hidden" value="{{key[3]}}">
                                    <button name="action" type="submit" class="btn btn-danger" value="remove">Remove</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="invoices" class="tab-pane active">
                <div class="col-md-12">
                    <h2>Personal invoices in the last 30 days</h2>
                    <table class="table table-hover table-condensed datatables dt-responsive" width="100%">
                        <thead>
                            <tr>
                                <th>Creation Date</th>
                                <th>ID</th>
                                <th>Destination</th>
                                <th>Price</th>
                                <th>Marketeer</th>
                                <th>Status</th>
                                <th>Link</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoice_table %}
                            <tr>
                                {% for info in invoice[1:] %}
                                <td class="{{invoice[0]}}">{{info}}</td>
                                {% endfor %}
                                <td class="{{invoice[0]}}">
                                    <form action="{{url_for('ordering.invoice', invoice_id=invoice[2])}}" method="get">
                                        <button type="submit" class="btn btn-success">Link</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/buyback.html
{% extends "base.html" %}
{% block head %}
{{super()}}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon_jf.ico') }}">
{% endblock head %}
{% block defaults %}
<script src="{{url_for('static', filename='datatables-buyback.js')}}"></script>
{% endblock defaults %}
{% block content %}
<div class="container-fluid">
    {% if not prices_usable %}
    <div class="row">
        <div class="alert alert-danger">
            Eve Central API is down. The prices below are not correct.
        </div>
    </div>
    {% endif %}
    {% for error in error_list %}
    <div class="row">
        <div class="alert alert-danger">
            {{error}}
        </div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-md-3">
            <form method="post" action="{{url_for('buyback.home')}}">
                <div class="form-group">
                    <label for="input">Copy-Paste from Hangar</label>
                    <textarea class="form-control" rows="25" id="input" name="input"></textarea>
                </div>
                {% if prices_usable %}
                <button type="submit" class="btn btn-primary" name="action" value="hangar_parse">Calculate</button>
                {% else %}
                <button type="submit" class="btn btn-primary" name="action" value="hangar_parse" disabled>Calculate</button>
                {% endif %}
            </form>
        </div>
        <div class="col-md-9">
            <h2>Contract Price: {{total_price}}</h2>
            <form method="post">
                <div class="form-group">
                    <input name="saved_input" value="{{input_string}}" hidden>
                    {% if input_string and prices_usable %}
                    <button type="submit" class="btn btn-success" name="action" value="quote">Save Quote</button>
                    {% else %}
                    <button type="submit" class="btn btn-success" name="action" value="quote" disabled>Save Quote</button>
                    {% endif %}
                </div>
            </form>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#quick">Quick</a></li>
                <li><a data-toggle="tab" href="#detailed">Detailed</a></li>
                <li><a data-toggle="tab" href="#refine">Refine</a></li>
                <li><a data-toggle="tab" href="#materials">Materials</a></li>
            </ul>
            <div class="tab-content">
                <div id="quick" class="tab-pane active">
                    <h3>Quick Prices</h3>
                    <table class="table table-hover table-condensed" id="buyback_quick">
                        <thead>
                        <tr>
                            {% for header in quick_table[0] %}
                            <th>{{header}}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for quick_stats in quick_table[1:] %}
                        <tr>
                            {% for info in quick_stats %}
                            <td>{{info}}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="detailed" class="tab-pane">
                    <h3>Detailed</h3>
                    <table class="table table-hover table-condensed datatables">
                        <thead>
                        <tr>
                            {% for header in price_table[0] %}
                            <th>{{header}}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for price_stats in price_table[1:] %}
                        <tr>
                            {% for info in price_stats %}
                            <td>{{info}}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="refine" class="tab-pane">
                    <h3>Refine</h3>
                    <table class="table table-hover table-condensed datatables">
                        <thead>
                        <tr>
                            {% for header in item_table[0] %}
                            <th>{{header}}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for item_stats in item_table[1:] %}
                        <tr>
                            {% for info in item_stats %}
                            <td>{{info}}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="materials" class="tab-pane">
                    <h3>Material Costs</h3>
                    <table class="table table-hover table-condensed datatables">
                        <thead>
                        <tr>
                            {% for header in material_table[0] %}
                            <th>{{header}}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for material_stats in material_table[1:] %}
                        <tr>
                            {% for info in material_stats %}
                            <td>{{info}}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/error.html
{% extends "base.html" %}
{% block head %}
{{super()}}
{% endblock head %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>{{error_code}} Error</h2>
            <h3>{{error_message}}</h3>
        </div>
    </div>
</div>
{% endblock content %}